### ISSUE TITLE
I would like to Remove Boney Boy.txt

### ISSUE THREAD

**Issue by tamusall** [tmusall/AdventCode#1]
This file serves no purpose why is it here???

**Comment by tmusall** [comment]
Dear Boney Boy,
Thank you for your interest in boney_boy.txt. Many have contributed to the success this project, so removing it would piss off way too many peeps. Your request is denied!
Have a Nice Day,
-Lil_D

**Comment by tamusall** [comment]
Please let me close my own issues, ok? This was my problem, not yours ok

**Comment by tmusall** [comment]
This is my github so my rules apply.
Keep da Peace,
-Lil-D

**Comment by tmusall** [comment]
Sup Boney?
